### ISSUE TITLE
NOT working anymore

### ISSUE THREAD

**Issue by frank392a** [keshavbhatt/ultimate-media-downloader-linux#10]
Hi,
this app is no longer working anymore. Whenever I try to download a playlist, it gets stack and will NOT List the Items on the play list

**Comment by keshavbhatt** [comment]
Please try to update the engine from setting section of the application. 
Thanks.

**Comment by frank392a** [comment]
Thank you!! That solved the problem!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
