### ISSUE TITLE
Activation Resolution

### ISSUE THREAD

**Issue by miksmit4** [keshavbhatt/ultimate-media-downloader-linux#12]
Software still not accepting license request. I'm using Ubuntu 22.04.2 LTS.

Software worked for trial period.

I close out of software and then reopen .

Then go to Account Tab and press Restore Account Tab. Software then rejects request! 

Account ID showing is: faadaedaf4f54a779582.

Reached out to below listed contact and have received no response.

Support at: 98378sub@gmail.com

**Comment by keshavbhatt** [comment]
Resolved via email.
