### ISSUE TITLE
error to download video user premium 

### ISSUE THREAD

**Issue by andrecintra77** [keshavbhatt/ultimate-media-downloader-linux#16]
I need support to fix this error [UMD4] Starting download...
[youtube] Extracting URL: https://www.youtube.com/watch?v=HDD5yofvwCI
[youtube] HDD5yofvwCI: Downloading webpage
[youtube] HDD5yofvwCI: Downloading android player API JSON
[info] HDD5yofvwCI: Downloading 1 format(s): 248+251
[dashsegments] Total fragments: 17
[download] Destination: Subindo Aplicação Do Zero no Azure-HDD5yofvwCI.f248.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
[dashsegments] Total fragments: 5
[download] Destination: Subindo Aplicação Do Zero no Azure-HDD5yofvwCI.f251.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
[UMD4] Done

**Comment by keshavbhatt** [comment]
Try to update engine in settings.

**Comment by andrecintra77** [comment]
Work fine after clean cache and update engine again !! Thank you !!

Em ter., 15 de ago. de 2023 às 01:52, Keshav Bhatt ***@***.***>
escreveu:
