### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by AnnieSixgun** [keshavbhatt/ultimate-media-downloader-linux#21]
I get this error using UMD4, but other downloader downloads video with no problem

[UMD4] Starting download...
[generic] Extracting URL: https://www.foodnetwork.com/recipes/ree-drummond/breakfast-grits-3755846
[generic] breakfast-grits-3755846: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
[UMD4] Done

**Comment by keshavbhatt** [comment]
You probably need authentication to access the resource. You can pass authentication cookies to Ultimate media downloader, see setting sections .
