### ISSUE TITLE
Bitchute no longer downloads.

### ISSUE THREAD

**Issue by Scrotalitch** [keshavbhatt/ultimate-media-downloader-linux#22]
Ever since bitchute introduced it's new format I can no longer download from there. I get this error:
'ERROR: [BitChute] Ons0Db0APSfk: Video is unavailable. Please make sure this video is playable in the browser before reporting this issue.' (the file is playing in my browser as we speak)

Great app though, will buy when trial period is over
Cheers -Pat

**Comment by Scrotalitch** [comment]
I have discovered a work-around. If I add the word 'old.' in front of 'bitchute' in the address bar I can get the old format and downloads work from there... thus this issue isn't so urgent... just letting you know it may not last, so maybe you can look into it for future purposes... Cheers

**Comment by keshavbhatt** [comment]
The problem was also solved in the download engine. Closing this.
