### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by frank392a** [keshavbhatt/ultimate-media-downloader-linux#24]
Hi, Is there any chance that you can implement a way to select the quality of the audio from best to worst?
And the other thing, it would be very nice that the app would create a folder with the name of the playlist that you are downloading. Like this app does : 
https://github.com/aandrew-me/ytDownloader

Thank you so very much!!

**Comment by keshavbhatt** [comment]
You can select amy combination of available video and audio formats. You need to click on list formats and then choose the desired formats and their combinations.
