### ISSUE TITLE
Your follow through and support is atrocious.

### ISSUE THREAD

**Issue by Scrotalitch** [keshavbhatt/ultimate-media-downloader-linux#27]
After discovering this app I was intitially well pleased and excited. Fully intending to buy a lifetime license.
But now that I see that you cannot be bothered to answer 'issues' that people (including myself) raise I find myself very reluctant to do this. The last two 'issues' that I raised have been ignored for over two weeks now...
Get your shit together and respond Keshav.  Great app - bullshit backup!!

**Comment by keshavbhatt** [comment]
Sorry for inconvenience. I checked the issues you have opened and i will provide fix in upcoming updates to the application.
