### ISSUE TITLE
Request for the source code of your project to be public.

### ISSUE THREAD

**Issue by mhogomchungu** [keshavbhatt/ultimate-media-downloader-linux#30]
Greetings,

Your project is a fork of [Media Downloader by mhogomchungu](https://github.com/mhogomchungu/media-downloader) or some of your code is derived from that project.

That project is mine and i released the sources under the terms of GPLv2+. Since you are using my work, your work becomes a derivative work of mine and hence subject to the terms of GPLv2+

Relevant sections of the licenses says the following
```
The fourth section for version 2 of the license and the seventh
 section of version 3 require that programs distributed as
 pre-compiled binaries be accompanied by a copy of the 
source code, a written offer to distribute the source code via 
the same mechanism as the pre-compiled binary, or the written 
offer to obtain the source code that the user got when they 
received the pre-compiled binary under the GPL. The second 
section of version 2 and the fifth section of version 3 also require
 giving "all recipients a copy of this License along with the 
Program". Version 3 of the license allows making the source code 
available in additional ways in fulfillment of the seventh section. 
These include downloading source code from an adjacent network 
server or by peer-to-peer transmission, provided that is how the 
compiled code was available and there are "clear directions" on 
where to find the source code.
```

I do not see where you are hosting your sources and i would like to have access to them.

This was discussed [here](https://github.com/mhogomchungu/media-downloader/issues/186)

**Comment by keshavbhatt** [comment]
Source code is public now.
