### ISSUE TITLE
I've downloaded to /tmp or to another mounted disk and it didn't work

### ISSUE THREAD

**Issue by BarbzYHOOL** [keshavbhatt/ultimate-media-downloader-linux#5]
So I set the general download path to my second mounted disk, it didn't start, it said "no permission"

The second time, I set it to "/tmp/" and it downloaded but the file was not findable, it wasn't there, but in UM4 it was shown as downloaded
I retried by setting "/tmp" without the last slash, and it acted exactly the same
Weird

So i've put it back to the original directory and it worked.

I need to change the path, my SSD is very small

**Comment by keshavbhatt** [comment]
**About writing to mounted drives**
To be able to download in mounted devices you need to enable the mount-observe permission run the following command to do the same or turn on the permission with whatever app store front you are using.
`snap connect ultimate-media-downloader:mount-observe`

**About writing to /tmp/** 
The /tmp/ for the snap app is not the /tmp you as a user see in snap world. snap apps uses their own /tmp folder which is not accessible by other applications or snaps. I will suggest to not use that as you download path. The snap app also cannot see your main /tmp folder for security reasons. So, you are not allowed to write into it.

**Comment by BarbzYHOOL** [comment]
Hey Keshav, i'm sorry i didn't mention it, but I installed UM4 from flathub (from the POP SHOP in fact)

i googled "flatpak mount-observe" but found nothing

**Comment by BarbzYHOOL** [comment]
Hey @keshavbhatt  i'm sorry i didn't mention it, but I installed UM4 from flathub (from the POP SHOP in fact)

i googled "flatpak mount-observe" but found nothing

**Comment by keshavbhatt** [comment]
Can you try 

`flatpak override --filesystem=/mnt/path-to-mounted-drive com.ktechpit.ultimate-media-downloader`

**Comment by BarbzYHOOL** [comment]
hey sorry, been very busy

what should I put in `--filesystem=/mnt/path-to-mounted-drive` ? `/tmp` ?

**Comment by BarbzYHOOL** [comment]
i tried with /tmp, or /tmp/ it doesn't work
