### ISSUE TITLE
Frozen :( 

### ISSUE THREAD

**Issue by frank392a** [keshavbhatt/ultimate-media-downloader-linux#7]
It was working perfectly until yesterday. today I try to use it and it is frozen cant select any of the tabs or ad a link it is dead :(  ok I try unistallg it and same result. btw Im using MX linux (no system D) .
Im getting this error : 
$ flatpak run com.ktechpit.ultimate-media-downloader
Gtk-Message: 17:50:01.564: Failed to load module "canberra-gtk-module"
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Previous instance of UMD4 seem to have crashed,trying to clean up before starting new one!

**Comment by keshavbhatt** [comment]
Thanks for opening this issue. I will provide a fix soon.

**Comment by keshavbhatt** [comment]
This is fixed in version 4.4
run `snap refresh ultimate-media-downloader` to force update the package if it was not automatically updated.

**Comment by frank392a** [comment]
Great news, thank you so very much!!!
Happy new year!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by keshavbhatt** [comment]
Right now i have limited the folder listing to load 100 recently downloaded items. There is a open in file manager button which can be used to quickly open the directory in system file manager in case user require to checkout older files. I will consider adding efficient way landing huge collection in near future.

**Comment by frank392a** [comment]
Hi Keshav Bhatt,
I think that option is unnecessary, because if someone wants to look at the downloaded file they are going to use a file manager.
One question, when is the new update is going to be ready at flathub?
Have a wonderful day!
Frank

________________________________
