### ISSUE TITLE
Make it easier to reactivate

### ISSUE THREAD

**Issue by frank392a** [keshavbhatt/ultimate-media-downloader-linux#8]
Please make it easier to reactivate the license!! Having to email you each time is not a good Idea. Remember this is Linux and Distro hopping is very common.

**Comment by keshavbhatt** [comment]
Hi @frank392a, I will consider making it easier :) In the meantime if you have reactivation request let me know via email.

Thanks for your feedback.

**Comment by frank392a** [comment]
Really, you need to change the way to restore the License. I have sent yo an Emal 1-10-23 and got no response. so I have sent you another Email for the same matter :( 
hope you have a very long life and be there to restore the licenses for everyone who bought the forever license :(
Thank you!!

**Comment by keshavbhatt** [comment]
Hi thank you for your feedback, I will try to figure out some ways to let users automatically restore their account. The hard part is, what if they will share their details to other users, no one will donate and everyone will start abusing this flaw. I don't use any kind of tracking to check all this and i dont consider adding any kind of tracking in my applications.Thats why the situation is like this.

**Comment by keshavbhatt** [comment]
Hi thank you for your feedback, I will try to figure out some ways to let users automatically restore their account. The hard part is, what if they will share their details to other users, no one will donate and everyone will start abusing this flaw. I don't use any kind of tracking to check all this and i dont consider adding any kind of tracking in my applications.Thats why the situation is like this.
